routes/web.php
    Route::delete('containers-destroy', [Admin\ContainerController::class,'massDestroy'])->name('containers.massDestroy');

    // Logical Flows
    Route::resource('logical-flows', Admin\LogicalFlowController::class);
    Route::delete('logical-flows-destroy', [Admin\LogicalFlowController::class,'massDestroy'])->name('logical-flows.massDestroy');

    // Certificates
    Route::resource('certificates', Admin\CertificateController::class);
    Route::delete('certificates-destroy', [Admin\CertificateController::class,'massDestroy'])->name('certificates.massDestroy');

    // Sites
    Route::resource('sites', Admin\SiteController::class);
    Route::get('sites-clone/{id}', [Admin\SiteController::class,'clone'])->name('sites.clone');
    Route::delete('sites-destroy', [Admin\SiteController::class,'massDestroy'])->name('sites.massDestroy');

    // Buildings
    Route::resource('buildings', Admin\BuildingController::class);
    Route::get('buildings-clone/{id}', [Admin\BuildingController::class,'clone'])->name('buildings.clone');
    Route::delete('buildings-destroy', [Admin\BuildingController::class,'massDestroy'])->name('buildings.massDestroy');

    // Bays
    Route::resource('bays', Admin\BayController::class);
    Route::get('bays-clone/{id}', [Admin\BayController::class,'clone'])->name('bays.clone');
    Route::delete('bays-destroy', [Admin\BayController::class,'massDestroy'])->name('bays.massDestroy');

    // Physical Servers
    Route::resource('physical-servers', Admin\PhysicalServerController::class);
    Route::get('physical-servers-clone/{id}', [Admin\PhysicalServerController::class,'clone'])->name('physical-servers.clone');
    Route::delete('physical-servers-destroy', [Admin\PhysicalServerController::class,'massDestroy'])->name('physical-servers.massDestroy');

    // Workstations
    Route::resource('workstations', Admin\WorkstationController::class);
    Route::get('workstations-clone/{id}', [Admin\WorkstationController::class,'clone'])->name('workstations.clone');
    Route::delete('workstations-destroy', [Admin\WorkstationController::class,'massDestroy'])->name('workstations.massDestroy');

    // Storage Devices
    Route::resource('storage-devices', Admin\StorageDeviceController::class);
    Route::delete('storage-devices-destroy', [Admin\StorageDeviceController::class,'massDestroy'])->name('storage-devices.massDestroy');

    // Peripherals
    Route::resource('peripherals', Admin\PeripheralController::class);
    Route::get('peripherals-clone/{id}', [Admin\PeripheralController::class,'clone'])->name('peripherals.clone');
    Route::delete('peripherals-destroy', [Admin\PeripheralController::class,'massDestroy'])->name('peripherals.massDestroy');

    // Phones
    Route::resource('phones', Admin\PhoneController::class);
    Route::get('phones-clone/{id}', [Admin\PhoneController::class,'clone'])->name('phones.clone');
    Route::delete('phones-destroy', [Admin\PhoneController::class,'massDestroy'])->name('phones.massDestroy');

    // Physical Switches
    Route::resource('physical-switches', Admin\PhysicalSwitchController::class);
    Route::get('physical-switches-clone/{id}', [Admin\PhysicalSwitchController::class,'clone'])->name('physical-switches.clone');
    Route::delete('physical-switches-destroy', [Admin\PhysicalSwitchController::class,'massDestroy'])->name('physical-switches.massDestroy');

    // Physical Routers
    Route::resource('physical-routers', Admin\PhysicalRouterController::class);
    Route::get('physical-routers-clone/{id}', [Admin\PhysicalRouterController::class,'clone'])->name('physical-routers.clone');
    Route::delete('physical-routers-destroy', [Admin\PhysicalRouterController::class,'massDestroy'])->name('physical-routers.massDestroy');

    // Wifi Terminals
    Route::resource('wifi-terminals', Admin\WifiTerminalController::class);
    Route::get('wifi-terminals-clone/{id}', [Admin\WifiTerminalController::class,'clone'])->name('wifi-terminals.clone');
    Route::delete('wifi-terminals-destroy', [Admin\WifiTerminalController::class,'massDestroy'])->name('wifi-terminals.massDestroy');

    // Physical Security Devices
    Route::resource('physical-security-devices', Admin\PhysicalSecurityDeviceController::class);
    Route::delete('physical-security-devices-destroy', [Admin\PhysicalSecurityDeviceController::class,'massDestroy'])->name('physical-security-devices.massDestroy');

    // Physical Links
    // TODO : check why it is not working with physical-links as resource name
    Route::resource('links', Admin\PhysicalLinkController::class);
    Route::delete('links-destroy', [Admin\PhysicalLinkController::class,'massDestroy'])->name('links.massDestroy');

    // WANs
    Route::resource('wans', Admin\WanController::class);
    Route::delete('wans-destroy', [Admin\WanController::class,'massDestroy'])->name('wans.massDestroy');

    // MANs
    Route::resource('mans', Admin\ManController::class);
    Route::delete('mans-destroy', [Admin\ManController::class,'massDestroy'])->name('mans.massDestroy');

    // LANs
    Route::resource('lans', Admin\LanController::class);
    Route::delete('lans-destroy', [Admin\LanController::class,'massDestroy'])->name('lans.massDestroy');

    // VLANs
    Route::resource('vlans', Admin\VlanController::class);
    Route::get('vlans/clone/{id}', [Admin\VlanController::class,'clone'])->name('vlans.clone');
    Route::delete('vlans-destroy', [Admin\VlanController::class,'massDestroy'])->name('vlans.massDestroy');

    // Application Modules
    Route::resource('application-modules', Admin\ApplicationModuleController::class);
    Route::delete('application-modules-destroy', [Admin\ApplicationModuleController::class,'massDestroy'])->name('application-modules.massDestroy');

    // Macro Processuses
    Route::resource('macro-processuses', Admin\MacroProcessusController::class);
    Route::delete('macro-processuses-destroy', [Admin\MacroProcessusController::class,'massDestroy'])->name('macro-processuses.massDestroy');

    // Global Search engine !
    Route::get('global-search', [Admin\GlobalSearchController::class,'search'])->name('globalSearch');

    // Certificate Configuration page
    Route::get('config/cert', [Admin\ConfigurationController::class,'getCertConfig'])->name('config.cert');
    Route::put('config/cert/save', [Admin\ConfigurationController::class,'saveCertConfig'])->name('config.cert.save');

    // CVE Configuration page
    Route::get('config/cve', [Admin\ConfigurationController::class,'getCVEConfig'])->name('config.cve');
    Route::put('config/cve/save', [Admin\ConfigurationController::class,'saveCVEConfig'])->name('config.cve.save');

    // Parameters
    Route::get('config/parameters', [Admin\ConfigurationController::class,'getParameters'])->name('config.parameters');
    Route::put('config/parameters/save', [Admin\ConfigurationController::class,'saveParameters'])->name('config.parameters.save');

    // Views
    // TODO : create a new class ViewController to reduce size of ReportController
    Route::get('report/gdpr', [Admin\ReportController::class, 'gdpr'])->name('report.gdpr');
    Route::get('report/ecosystem', [Admin\ReportController::class,'ecosystem'])->name('report.view.ecosystem');
    Route::get('report/information_system', [Admin\ReportController::class,'informationSystem'])->name('report.view.informaton-system');
    Route::get('report/administration', [Admin\ReportController::class,'administration'])->name('report.view.administration');
    Route::get('report/applications', [Admin\ReportController::class,'applications'])->name('report.view.applications');
    Route::get('report/application_flows', [Admin\ReportController::class,'applicationFlows'])->name('report.view.application-flows');
    Route::get('report/logical_infrastructure', [Admin\ReportController::class,'logicalInfrastructure'])->name('report.view.logical-infrastructure');
    Route::get('report/physical_infrastructure', [Admin\ReportController::class,'physicalInfrastructure'])->name('report.view.physical-infrastructure');
    Route::get('report/network_infrastructure', [Admin\ReportController::class,'networkInfrastructure'])->name('report.view.network-infrastructure');

    // Experimental views
    Route::get('report/zones', [Admin\ReportController::class,'zones'])->name('report.view.zones');

    // Graphs
    Route::resource('graphs', Admin\GraphController::class);
    Route::put('graph/save', [Admin\GraphController::class,'save']);
    Route::delete('graphs-destroy', [Admin\GraphController::class,'massDestroy'])->name('graphs.massDestroy');
    Route::get('graphs/clone/{id}', [Admin\GraphController::class,'clone'])->name('graphs.clone');

    // Explorer
    Route::get('report/explore', [Admin\ExplorerController::class,'explore'])->name('report.explore');

    // Maturity levels
    Route::get('report/maturity1', [Admin\HomeController::class,'maturity1'])->name('report.maturity1');
    Route::get('report/maturity2', [Admin\HomeController::class,'maturity2'])->name('report.maturity2');
    Route::get('report/maturity3', [Admin\HomeController::class,'maturity3'])->name('report.maturity3');

    // Reporting
    Route::put('report/cartography', [Admin\CartographyController::class, 'cartography'])->name('report.cartography');
    Route::get('report/entities', [Admin\ReportController::class,'entities'])->name('report.entities');
    Route::get('report/applicationsByBlocks', [Admin\ReportController::class,'applicationsByBlocks'])->name('report.applicationsByBlocks');
    Route::get('report/logicalServers', [Admin\ReportController::class,'logicalServers'])->name('report.logicalServers');
    Route::get('report/securityNeeds', [Admin\ReportController::class, 'securityNeeds'])->name('report.securityNeeds');
    Route::get('report/logicalServerConfigs', [Admin\ReportController::class, 'logicalServerConfigs'])->name('report.logicalServerConfigs');

app/Http/Controllers/API/PhysicalRouterController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyPhysicalRouterRequest;
use App\Http\Requests\StorePhysicalRouterRequest;
use App\Http\Requests\UpdatePhysicalRouterRequest;
use App\Http\Resources\Admin\PhysicalRouterResource;
use App\PhysicalRouter;
use Gate;
use Illuminate\Http\Response;

class PhysicalRouterController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('physical_router_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $physicalrouters = PhysicalRouter::all();

        return response()->json($physicalrouters);
    }

    public function store(StorePhysicalRouterRequest $request)
    {
        abort_if(Gate::denies('physical_router_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $physicalrouter = PhysicalRouter::create($request->all());
        $physicalrouter->vlans()->sync($request->input('vlans', []));
        // syncs
        // $physicalrouter->roles()->sync($request->input('roles', []));

        return response()->json($physicalrouter, 201);
    }

    public function show(PhysicalRouter $physicalRouter)
    {
        abort_if(Gate::denies('physical_router_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return new PhysicalRouterResource($physicalRouter);
    }

    public function update(UpdatePhysicalRouterRequest $request, PhysicalRouter $physicalRouter)
    {
        abort_if(Gate::denies('physical_router_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $physicalRouter->update($request->all());
        $physicalRouter->vlans()->sync($request->input('vlans', []));
        // syncs
        // $physicalrouter->roles()->sync($request->input('roles', []));

        return response()->json();
    }

    public function destroy(PhysicalRouter $physicalRouter)
    {
        abort_if(Gate::denies('physical_router_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $physicalRouter->delete();

        return response()->json();
    }

    public function massDestroy(MassDestroyPhysicalRouterRequest $request)
    {
        abort_if(Gate::denies('physical_router_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        PhysicalRouter::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

app/Http/Controllers/Admin/PhysicalRouterController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Bay;
use App\Building;
use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyPhysicalRouterRequest;
use App\Http\Requests\StorePhysicalRouterRequest;
use App\Http\Requests\UpdatePhysicalRouterRequest;
use App\PhysicalRouter;
use App\Router;
use App\Site;
use App\Vlan;
use Gate;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class PhysicalRouterController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('physical_router_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $physicalRouters = PhysicalRouter::all();

        return view('admin.physicalRouters.index', compact('physicalRouters'));
    }

    public function create()
    {
        abort_if(Gate::denies('physical_router_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $sites = Site::all()->sortBy('name')->pluck('name', 'id');
        $buildings = Building::all()->sortBy('name')->pluck('name', 'id');
        $bays = Bay::all()->sortBy('name')->pluck('name', 'id');
        $routers = Router::all()->sortBy('name')->pluck('name', 'id');

        $vlans = Vlan::all()->sortBy('name')->pluck('name', 'id');

        $type_list = PhysicalRouter::select('type')->where('type', '<>', null)->distinct()->orderBy('type')->pluck('type');

        return view(
            'admin.physicalRouters.create',
            compact('sites', 'buildings', 'bays', 'routers', 'vlans', 'type_list')
        );
    }

    public function clone(Request $request)
    {
        abort_if(Gate::denies('physical_router_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $sites = Site::all()->sortBy('name')->pluck('name', 'id');
        $buildings = Building::all()->sortBy('name')->pluck('name', 'id');
        $bays = Bay::all()->sortBy('name')->pluck('name', 'id');
        $routers = Router::all()->sortBy('name')->pluck('name', 'id');

        $vlans = Vlan::all()->sortBy('name')->pluck('name', 'id');

        $type_list = PhysicalRouter::select('type')->where('type', '<>', null)->distinct()->orderBy('type')->pluck('type');

        // Get PhysicalRouter
        $physicalRouter = PhysicalRouter::find($request->id);

        // PhysicalRouter not found
        abort_if($physicalRouter === null, Response::HTTP_NOT_FOUND, '404 Not Found');

        $request->merge($physicalRouter->only($physicalRouter->getFillable()));
        $request->merge(['vlans' => $physicalRouter->vlans()->pluck('id')->unique()->toArray()]);
        $request->merge(['routers' => $physicalRouter->routers()->pluck('id')->unique()->toArray()]);
        $request->flash();

        return view(
            'admin.physicalRouters.create',
            compact('sites', 'buildings', 'bays', 'routers', 'vlans', 'type_list')
        );
    }

    public function store(StorePhysicalRouterRequest $request)
    {
        $physicalRouter = PhysicalRouter::create($request->all());
        $physicalRouter->vlans()->sync($request->input('vlans', []));
        $physicalRouter->routers()->sync($request->input('routers', []));

        return redirect()->route('admin.physical-routers.index');
    }

    public function edit(PhysicalRouter $physicalRouter)
    {
        abort_if(Gate::denies('physical_router_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $sites = Site::all()->sortBy('name')->pluck('name', 'id');
        $buildings = Building::all()->sortBy('name')->pluck('name', 'id');
        $bays = Bay::all()->sortBy('name')->pluck('name', 'id');
        $vlans = Vlan::all()->sortBy('name')->pluck('name', 'id');
        $routers = Router::all()->sortBy('name')->pluck('name', 'id');

        $type_list = PhysicalRouter::select('type')->where('type', '<>', null)->distinct()->orderBy('type')->pluck('type');

        $physicalRouter->load('site', 'building', 'bay', 'vlans');

        return view(
            'admin.physicalRouters.edit',
            compact('sites', 'buildings', 'bays', 'vlans', 'physicalRouter', 'routers', 'type_list')
        );
    }

    public function update(UpdatePhysicalRouterRequest $request, PhysicalRouter $physicalRouter)
    {
        $physicalRouter->update($request->all());
        $physicalRouter->vlans()->sync($request->input('vlans', []));
        $physicalRouter->routers()->sync($request->input('routers', []));

        return redirect()->route('admin.physical-routers.index');
    }

    public function show(PhysicalRouter $physicalRouter)
    {
        abort_if(Gate::denies('physical_router_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $physicalRouter->load('site', 'building', 'bay', 'vlans');

        return view('admin.physicalRouters.show', compact('physicalRouter'));
    }

    public function destroy(PhysicalRouter $physicalRouter)
    {
        abort_if(Gate::denies('physical_router_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $physicalRouter->delete();

        return redirect()->route('admin.physical-routers.index');
    }

    public function massDestroy(MassDestroyPhysicalRouterRequest $request)
    {
        PhysicalRouter::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/physicalRouters/index.blade.php
@extends('layouts.admin')
@section('content')
@can('physical_router_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.physical-routers.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.physicalRouter.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.physicalRouter.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table id="dataTable" class="table table-bordered table-striped table-hover datatable">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.physicalRouter.fields.name') }}
                        </th>
                        <th>
                            {{ trans('cruds.physicalRouter.fields.type') }}
                        </th>
                        <th>
                            {{ trans('cruds.physicalRouter.fields.description') }}
                        </th>
                        <th>
                            {{ trans('cruds.physicalRouter.fields.site') }}
                        </th>
                        <th>
                            {{ trans('cruds.physicalRouter.fields.building') }}
                        </th>
                        <th>
                            {{ trans('cruds.physicalRouter.fields.bay') }}
                        </th>
                        <th>
                            {{ trans('cruds.physicalRouter.fields.routers') }}
                        </th>
                      <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($physicalRouters as $key => $physicalRouter)
                        <tr data-entry-id="{{ $physicalRouter->id }}">
                            <td>

                            </td>
                            <td>
                                <a href="{{ route('admin.physical-routers.show', $physicalRouter->id) }}">
                                {{ $physicalRouter->name ?? '' }}
                                </a>
                            </td>
                            <td>
                                {{ $physicalRouter->type ?? '' }}
                            </td>
                            <td>
                                {!! $physicalRouter->description ?? '' !!}
                            </td>
                            <td>
                                @if($physicalRouter->site!=null)
                                <a href="{{ route('admin.sites.show', $physicalRouter->site->id) }}">
                                    {{ $physicalRouter->site->name ?? '' }}
                                </a>
                                @endif
                            </td>
                            <td>
                                @if($physicalRouter->building!=null)
                                <a href="{{ route('admin.buildings.show', $physicalRouter->building->id) }}">
                                    {{ $physicalRouter->building->name ?? '' }}
                                </a>
                                @endif
                            </td>
                            <td>
                                @if($physicalRouter->bay!=null)
                                <a href="{{ route('admin.bays.show', $physicalRouter->bay->id) }}">
                                    {{ $physicalRouter->bay->name ?? '' }}
                                </a>
                                @endif
                            </td>
                            <td>
                                @foreach($physicalRouter->routers as $router)
                                    <a href="{{ route('admin.routers.show', $router->id) }}">
                                    {{ $router->name }}
                                    @if(!$loop->last)
                                    ,
                                    @endif
                                    </a>
                                @endforeach
                            </td>
                            <td nowrap>
                                @can('physical_router_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.physical-routers.show', $physicalRouter->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('physical_router_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.physical-routers.edit', $physicalRouter->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('physical_router_delete')
                                    <form action="{{ route('admin.physical-routers.destroy', $physicalRouter->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection

@section('scripts')
@parent
<script>
@include('partials.datatable', array(
    'id' => '#dataTable',
    'title' => trans("cruds.physicalRouter.title_singular"),
    'URL' => route('admin.physical-routers.massDestroy'),
    'canDelete' => auth()->user()->can('physical_router_delete') ? true : false
));
</script>
@endsection

resources/views/admin/physicalRouters/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="form-group">
    <a class="btn btn-default" href="{{ route('admin.physical-routers.index') }}">
        {{ trans('global.back_to_list') }}
    </a>

    <a class="btn btn-success" href="{{ route('admin.report.explore') }}?node=PROUTER_{{$physicalRouter->id}}">
        {{ trans('global.explore') }}
    </a>

    @can('physical_router_edit')
        <a class="btn btn-info" href="{{ route('admin.physical-routers.edit', $physicalRouter->id) }}">
            {{ trans('global.edit') }}
        </a>
    @endcan

    @can('physical_router_create')
        <a class="btn btn-warning" href="{{ route('admin.physical-routers.clone', $physicalRouter->id) }}">
            {{ trans('global.clone') }}
        </a>
    @endcan

    @can('physical_router_delete')
        <form action="{{ route('admin.physical-routers.destroy', $physicalRouter->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <input type="submit" class="btn btn-danger" value="{{ trans('global.delete') }}">
        </form>
    @endcan

</div>

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.physicalRouter.title') }}
    </div>

    <div class="card-body">
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th width="10%">
                            {{ trans('cruds.physicalRouter.fields.name') }}
                        </th>
                        <td>
                            {{ $physicalRouter->name }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.physicalRouter.fields.type') }}
                        </th>
                        <td>
                            {{ $physicalRouter->type }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.physicalRouter.fields.description') }}
                        </th>
                        <td>
                            {!! $physicalRouter->description !!}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.physicalRouter.fields.site') }}
                        </th>
                        <td>
                            @if ($physicalRouter->site!=null)
                                <a href="{{ route('admin.sites.show', $physicalRouter->site->id) }}">
                                {{ $physicalRouter->site->name ?? '' }}
                                </a>
                            @endif
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.physicalRouter.fields.building') }}
                        </th>
                        <td>
                            @if ($physicalRouter->building!=null)
                                <a href="{{ route('admin.buildings.show', $physicalRouter->building->id) }}">
                                {{ $physicalRouter->building->name ?? '' }}
                                </a>
                            @endif
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.physicalRouter.fields.bay') }}
                        </th>
                        <td>
                            @if ($physicalRouter->bay!=null)
                                <a href="{{ route('admin.bays.show', $physicalRouter->bay->id) }}">
                                {{ $physicalRouter->bay->name ?? '' }}
                                </a>
                            @endif
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.physicalRouter.fields.routers') }}
                        </th>
                        <td>
                            @foreach($physicalRouter->routers as $router)
                                <a href="{{ route('admin.routers.show', $router->id) }}">
                                {{ $router->name }}
                                @if(!$loop->last)
                                ,
                                @endif
                                </a>
                            @endforeach
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.physicalRouter.fields.vlan') }}
                        </th>
                        <td>
                            @foreach($physicalRouter->vlans as $vlan)
                                <a href="{{ route('admin.vlans.show', $vlan->id) }}">
                                {{ $vlan->name }}
                                @if(!$loop->last)
                                ,
                                @endif
                                </a>
                            @endforeach
                        </td>
                    </tr>
                </tbody>
            </table>
    </div>
    <div class="card-footer">
        {{ trans('global.created_at') }} {{ $physicalRouter->created_at ? $physicalRouter->created_at->format(trans('global.timestamp')) : '' }} |
        {{ trans('global.updated_at') }} {{ $physicalRouter->updated_at ? $physicalRouter->updated_at->format(trans('global.timestamp')) : '' }}
    </div>
</div>
<div class="form-group">
    <a class="btn btn-default" href="{{ route('admin.physical-routers.index') }}">
        {{ trans('global.back_to_list') }}
    </a>
</div>
@endsection