routes/web.php
<?php

use App\Http\Controllers;
use App\Http\Controllers\Admin;

Route::redirect('/', '/login');

Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

// Authentification routes
Auth::routes([
    'login' => true,
    'logout' => true,
    'register' => false, // Désactiver l'inscription
    'reset' => false, // Custom version
    'confirm' => false, // Désactiver la confirmation de mot de passe
    'verify' => false, // Désactiver la vérification par e-mail
]);

// Forget password
Route::get('forget-password', [App\Http\Controllers\Auth\ForgotPasswordController::class, 'showForgetPasswordForm'])->name('forget.password.get');
Route::post('forget-password', [App\Http\Controllers\Auth\ForgotPasswordController::class, 'submitForgetPasswordForm'])->name('forget.password.post');
Route::get('reset-password/{token}', [App\Http\Controllers\Auth\ForgotPasswordController::class, 'showResetPasswordForm'])->name('reset.password.get');
Route::post('reset-password', [App\Http\Controllers\Auth\ForgotPasswordController::class, 'submitResetPasswordForm'])->name('reset.password.post');

// keycloak
Route::get('login/keycloak', [App\Http\Controllers\Auth\SsoController::class,'redirectToKeycloak'])->name('login.keycloak');
Route::get('login/keycloak/callback', [App\Http\Controllers\Auth\SsoController::class,'handleKeycloakCallback']);

// Admin
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth']], function () {
    // Dashboard
    Route::get('/', [Admin\HomeController::class,'index'])->name('home');

    // Test page
    Route::get('/test', function () {
        return view('test');
    });

    // Roles
    Route::resource('roles', Admin\RolesController::class);
    Route::delete('roles-destroy', [Admin\RolesController::class,'massDestroy'])->name('roles.massDestroy');

    // Users
    Route::resource('users', Admin\UsersController::class);
    Route::delete('users-destroy', [Admin\UsersController::class,'massDestroy'])->name('users.massDestroy');

    // DataProcessing
    Route::resource('data-processings', Admin\DataProcessingController::class);
    Route::delete('data-processings-destroy', [Admin\DataProcessingController::class,'massDestroy'])->name('data-processings.massDestroy');

    // SecurityControls
    Route::resource('security-controls', Admin\SecurityControlController::class);
    Route::delete('security-controls-destroy', [Admin\SecurityControlController::class,'massDestroy'])->name('security-controls.massDestroy');
    Route::get('security-controls-assign', [Admin\SecurityControlController::class,'assign'])->name('security-controls.assign');
    Route::get('security-controls-list', [Admin\SecurityControlController::class,'list'])->name('security-controls.list');
    Route::put('security-controls-associate', [Admin\SecurityControlController::class,'associate'])->name('security-controls-associate');

    // Entities
    Route::resource('entities', Admin\EntityController::class);
    Route::delete('entities-destroy', [Admin\EntityController::class,'massDestroy'])->name('entities.massDestroy');

    // Relations
    Route::resource('relations', Admin\RelationController::class);
    Route::delete('relations-destroy', [Admin\RelationController::class,'massDestroy'])->name('relations.massDestroy');

    // Processes
    Route::resource('processes', Admin\ProcessController::class);
    Route::delete('processes-destroy', [Admin\ProcessController::class,'massDestroy'])->name('processes.massDestroy');

    // Operations
    Route::resource('operations', Admin\OperationController::class);
    Route::delete('operations-destroy', [Admin\OperationController::class,'massDestroy'])->name('operations.massDestroy');

    // Actors
    Route::resource('actors', Admin\ActorController::class);
    Route::delete('actors-destroy', [Admin\ActorController::class,'massDestroy'])->name('actors.massDestroy');

    // Activities
    Route::resource('activities', Admin\ActivityController::class);
    Route::delete('activities-destroy', [Admin\ActivityController::class,'massDestroy'])->name('activities.massDestroy');

    // Tasks
    Route::resource('tasks', Admin\TaskController::class);
    Route::delete('tasks-destroy', [Admin\TaskController::class,'massDestroy'])->name('tasks.massDestroy');

    // Information
    Route::resource('information', Admin\InformationController::class);
    Route::delete('information-destroy', [Admin\InformationController::class,'massDestroy'])->name('information.massDestroy');

    // Application Blocks
    Route::resource('application-blocks', Admin\ApplicationBlockController::class);
    Route::delete('application-blocks-destroy', [Admin\ApplicationBlockController::class,'massDestroy'])->name('application-blocks.massDestroy');

    // Applications
    Route::resource('applications', Admin\MApplicationController::class);
    Route::get('application-icon/{id}', [Admin\MApplicationController::class,'icon'])->name('application-icon');
    Route::delete('applications-destroy', [Admin\MApplicationController::class,'massDestroy'])->name('applications.massDestroy');

    // Application Services
    Route::resource('application-services', Admin\ApplicationServiceController::class);
    Route::delete('application-services-destroy', [Admin\ApplicationServiceController::class,'massDestroy'])->name('application-services.massDestroy');

    // Application Events
    Route::resource('application-events', Admin\MApplicationEventController::class);

    // Databases
    Route::resource('databases', Admin\DatabaseController::class);
    Route::delete('databases-destroy', [Admin\DatabaseController::class,'massDestroy'])->name('databases.massDestroy');

    // Fluxes
    Route::resource('fluxes', Admin\FluxController::class);
    Route::delete('fluxes-destroy', [Admin\FluxController::class,'massDestroy'])->name('fluxes.massDestroy');

    // Zone Admins
    Route::resource('zone-admins', Admin\ZoneAdminController::class);
    Route::delete('zone-admins-destroy', [Admin\ZoneAdminController::class,'massDestroy'])->name('zone-admins.massDestroy');

    // Annuaires
    Route::resource('annuaires', Admin\AnnuaireController::class);
    Route::delete('annuaires-destroy', [Admin\AnnuaireController::class,'massDestroy'])->name('annuaires.massDestroy');

    // Forest Ads
    Route::resource('forest-ads', Admin\ForestAdController::class);
    Route::delete('forest-ads-destroy', [Admin\ForestAdController::class,'massDestroy'])->name('forest-ads.massDestroy');

    // Domaine Ads
    Route::resource('domaine-ads', Admin\DomaineAdController::class);
    Route::delete('domaine-ads-destroy', [Admin\DomaineAdController::class,'massDestroy'])->name('domaine-ads.massDestroy');

    // Admin User
    Route::resource('admin-users', Admin\AdminUserController::class);
    Route::delete('admin-users-destroy', [Admin\AdminUserController::class,'massDestroy'])->name('admin-users.massDestroy');

    // Networks
    Route::resource('networks', Admin\NetworkController::class);
    Route::delete('networks-destroy', [Admin\NetworkController::class,'massDestroy'])->name('networks.massDestroy');

    // Subnetworks
    Route::resource('subnetworks', Admin\SubnetworkController::class);
    Route::delete('subnetworks-destroy', [Admin\SubnetworkController::class,'massDestroy'])->name('subnetworks.massDestroy');

    // Gateways
    Route::resource('gateways', Admin\GatewayController::class);
    Route::delete('gateways-destroy', [Admin\GatewayController::class,'massDestroy'])->name('gateways.massDestroy');

    // External Connected Entities
    Route::resource('external-connected-entities', Admin\ExternalConnectedEntityController::class);
    Route::delete('external-connected-entities-destroy', [Admin\ExternalConnectedEntityController::class,'massDestroy'])->name('external-connected-entities.massDestroy');

    // Network Switches
    Route::resource('network-switches', Admin\NetworkSwitchController::class);
    Route::delete('network-switches-destroy', [Admin\NetworkSwitchController::class,'massDestroy'])->name('network-switches.massDestroy');

    // Routers
    Route::resource('routers', Admin\RouterController::class);
    Route::delete('routers-destroy', [Admin\RouterController::class,'massDestroy'])->name('routers.massDestroy');

    // Security Devices
    Route::resource('security-devices', Admin\SecurityDeviceController::class);
    Route::delete('security-devices-destroy', [Admin\SecurityDeviceController::class,'massDestroy'])->name('security-devices.massDestroy');

    // Dhcp Servers
    Route::resource('dhcp-servers', Admin\DhcpServerController::class);
    Route::delete('dhcp-servers-destroy', [Admin\DhcpServerController::class,'massDestroy'])->name('dhcp-servers.massDestroy');

    // Dnsservers
    Route::resource('dnsservers', Admin\DnsserverController::class);
    Route::delete('dnsservers-destroy', [Admin\DnsserverController::class,'massDestroy'])->name('dnsservers.massDestroy');

    // Clusters
    Route::resource('clusters', Admin\ClusterController::class);
    Route::delete('clusters-destroy', [Admin\ClusterController::class,'massDestroy'])->name('clusters.massDestroy');

    // Logical Servers
    Route::resource('logical-servers', Admin\LogicalServerController::class);
    Route::delete('logical-servers-destroy', [Admin\LogicalServerController::class,'massDestroy'])->name('logical-servers.massDestroy');

    // Containers
    Route::resource('containers', Admin\ContainerController::class);
    Route::delete('containers-destroy', [Admin\ContainerController::class,'massDestroy'])->name('containers.massDestroy');

    // Logical Flows
    Route::resource('logical-flows', Admin\LogicalFlowController::class);
    Route::delete('logical-flows-destroy', [Admin\LogicalFlowController::class,'massDestroy'])->name('logical-flows.massDestroy');

    // Certificates

app/Http/Controllers/API/ProcessController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyProcessRequest;
use App\Http\Requests\StoreProcessRequest;
use App\Http\Requests\UpdateProcessRequest;
use App\Http\Resources\Admin\ProcessResource;
use App\Operation;
use App\Process;
use Gate;
use Illuminate\Http\Response;

class ProcessController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('process_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $processs = Process::all();

        return response()->json($processs);
    }

    public function store(StoreProcessRequest $request)
    {
        abort_if(Gate::denies('process_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $process = Process::create($request->all());
        $process->activities()->sync($request->input('activities', []));
        $process->entities()->sync($request->input('entities', []));
        $process->information()->sync($request->input('informations', []));
        $process->applications()->sync($request->input('applications', []));
        Operation::whereIn('id', $request->input('operations', []))
            ->update(['process_id' => $process->id]);

        return response()->json($process, 201);
    }

    public function show(Process $process)
    {
        abort_if(Gate::denies('process_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return new ProcessResource($process);
    }

    public function update(UpdateProcessRequest $request, Process $process)
    {
        abort_if(Gate::denies('process_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $process->update($request->all());
        if ($request->has('activities')) {
            $process->activities()->sync($request->input('activities', []));
        }
        if ($request->has('entities')) {
            $process->entities()->sync($request->input('entities', []));
        }
        if ($request->has('informations')) {
            $process->information()->sync($request->input('informations', []));
        }
        if ($request->has('applications')) {
            $process->applications()->sync($request->input('applications', []));
        }
        if ($request->has('operations')) {
            Operation::whereIn('id', $request->input('operations', []))
                ->update(['process_id' => $process->id]);
        }

        return response()->json();
    }

    public function destroy(Process $process)
    {
        abort_if(Gate::denies('process_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $process->delete();

        return response()->json();
    }

    public function massDestroy(MassDestroyProcessRequest $request)
    {
        abort_if(Gate::denies('process_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        Process::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/processes/index.blade.php
@extends('layouts.admin')
@section('content')
@can('process_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.processes.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.process.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.process.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table id="dataTable" class="table table-bordered table-striped table-hover datatable">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.process.fields.name') }}
                        </th>
                        <th>
                            {{ trans('cruds.process.fields.description') }}
                        </th>
                        <th>
                            {{ trans('cruds.process.fields.operations') }}
                        </th>
                        <th>
                            {{ trans('cruds.process.fields.activities') }}
                        </th>
                        <th>
                            {{ trans('cruds.process.fields.informations') }}
                        </th>
                        <th>
                            {{ trans('cruds.process.fields.macroprocessus') }}
                        </th>
                        <th>
                            {{ trans('cruds.process.fields.owner') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($processes as $key => $process)
                        <tr data-entry-id="{{ $process->id }}"
                            @if(($process->name==null)||
                                ($process->description==null)||
                                ($process->in_out==null)||
                                ((auth()->user()->granularity>=2)&&
                                    (($process->security_need_c==null)||
                                    ($process->security_need_i==null)||
                                    ($process->security_need_a==null)||
                                    ($process->security_need_t==null)))||
                                ($process->owner==null)||
                                ($process->macroprocess_id==null)
                                )
                                                      class="table-warning"
                            @endif

                            >
                            <td>

                            </td>
                            <td>
                                <a href="{{ route('admin.processes.show', $process->id) }}">
                                {{ $process->name ?? '' }}
                                </a>
                            </td>
                            <td>
                                {!! $process->description ?? '' !!}
                            </td>
                            <td>
                                {!!
                                    $process->operations->map(function ($operation) {
                                        return '<a href="' . route('admin.operations.show', $operation->id) . '">' . $operation->name . '</a>';
                                    })->implode(', ');
                                !!}
                            </td>
                            <td>
                                {!!
                                    $process->activities->map(function ($activity) {
                                        return '<a href="' . route('admin.activities.show', $activity->id) . '">' . $activity->name . '</a>';
                                    })->implode(', ');
                                !!}
                            </td>
                            <td>
                                {!!
                                    $process->information->map(function ($information) {
                                        return '<a href="' . route('admin.information.show', $information->id) . '">' . $information->name . '</a>';
                                    })->implode(', ');
                                !!}
                            </td>
                            <td>
                                @if ($process->macroprocess_id!=null)
                                <a href="{{ route('admin.macro-processuses.show', $process->macroprocess_id) }}">
                                {{ $process->macroProcess->name ?? '' }}
                                </a>
                                @endif
                            </td>
                            <td>
                                {{ $process->owner ?? '' }}
                            </td>
                            <td nowrap>
                                @can('process_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.processes.show', $process->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('process_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.processes.edit', $process->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('process_delete')
                                    <form action="{{ route('admin.processes.destroy', $process->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
@include('partials.datatable', array(
    'id' => '#dataTable',
    'title' => trans("cruds.process.title_singular"),
    'URL' => route('admin.processes.massDestroy'),
    'canDelete' => auth()->user()->can('process_delete') ? true : false
));
</script>
@endsection

resources/views/admin/processes/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="form-group">
    <a class="btn btn-default" href="{{ route('admin.processes.index') }}">
        {{ trans('global.back_to_list') }}
    </a>

    <a class="btn btn-success" href="{{ route('admin.report.explore') }}?node=PROCESS_{{$process->id}}">
        {{ trans('global.explore') }}
    </a>

    @can('process_edit')
        <a class="btn btn-info" href="{{ route('admin.processes.edit', $process->id) }}">
            {{ trans('global.edit') }}
        </a>
    @endcan

    @can('process_delete')
        <form action="{{ route('admin.processes.destroy', $process->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <input type="submit" class="btn btn-danger" value="{{ trans('global.delete') }}">
        </form>
    @endcan

</div>

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.process.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th width="10%">
                            {{ trans('cruds.process.fields.name') }}
                        </th>
                        <td colspan="2">
                            {{ $process->name }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.process.fields.description') }}
                        </th>
                        <td>
                            {!! $process->description !!}
                        </td>
                        <td width="10%">
                            @if ($process->icon_id === null)
                            <img src='/images/process.png' width='120' height='120'>
                            @else
                            <img src='{{ route('admin.documents.show', $process->icon_id) }}' width='120' height='120'>
                            @endif
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.process.fields.in_out') }}
                        </th>
                        <td colspan="2">
                            {!! $process->in_out !!}
                        </td>
                    </tr>
                    @if (auth()->user()->granularity>=3)
                    <tr>
                        <th>
                            {{ trans('cruds.process.fields.activities') }}
                        </th>
                        <td colspan="2">
                            @foreach($process->activities as $activity)
                                <a href="{{ route('admin.activities.show', $activity->id) }}">
                                {{ $activity->name }}
                                </a>
                                @if (!$loop->last)
                                ,
                                @endif
                            @endforeach
                        </td>
                    </tr>
                    @endif
                    <tr>
                        <th>
                            {{ trans('cruds.process.fields.entities') }}
                        </th>
                        <td colspan="2">
                            @foreach($process->entities as $entity)
                                <a href="{{ route('admin.entities.show', $entity->id) }}">
                                {{ $entity->name }}
                                </a>
                                @if (!$loop->last)
                                ,
                                @endif
                            @endforeach
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.process.fields.informations') }}
                        </th>
                        <td colspan="2">
                            @foreach($process->information as $info)
                                <a href="{{ route('admin.information.show', $info->id) }}">
                                {{ $info->name }}
                                </a>
                                @if (!$loop->last)
                                ,
                                @endif
                            @endforeach
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.process.fields.security_need') }}
                        </th>
                        <td colspan="2">
                        {{ trans('global.confidentiality') }} :
                            @if ($process->security_need_c==0){{ trans('global.none') }}@endif
                            @if ($process->security_need_c==1)<span class="veryLowRisk">{{ trans('global.low') }}</span>@endif
                            @if ($process->security_need_c==2)<span class="lowRisk">{{ trans('global.medium') }}</span>@endif
                            @if ($process->security_need_c==3)<span class="mediumRisk">{{ trans('global.strong') }}</span>@endif
                            @if ($process->security_need_c==4)<span class="highRisk">{{ trans('global.very_strong') }}</span>@endif
                        &nbsp;
                        {{ trans('global.integrity') }} :
                            @if ($process->security_need_i==0){{ trans('global.none') }}@endif
                            @if ($process->security_need_i==1)<span class="veryLowRisk">{{ trans('global.low') }}</span>@endif
                            @if ($process->security_need_i==2)<span class="lowRisk">{{ trans('global.medium') }}</span>@endif
                            @if ($process->security_need_i==3)<span class="mediumRisk">{{ trans('global.strong') }}</span>@endif
                            @if ($process->security_need_i==4)<span class="highRisk">{{ trans('global.very_strong') }}</span>@endif
                        &nbsp;
                        {{ trans('global.availability') }} :
                            @if ($process->security_need_a==0){{ trans('global.none') }}@endif
                            @if ($process->security_need_a==1)<span class="veryLowRisk">{{ trans('global.low') }}</span>@endif
                            @if ($process->security_need_a==2)<span class="lowRisk">{{ trans('global.medium') }}</span>@endif
                            @if ($process->security_need_a==3)<span class="mediumRisk">{{ trans('global.strong') }}</span>@endif
                            @if ($process->security_need_a==4)<span class="highRisk">{{ trans('global.very_strong') }}</span>@endif
                        &nbsp;
                        {{ trans('global.tracability') }} :
                            @if ($process->security_need_t==0){{ trans('global.none') }}@endif
                            @if ($process->security_need_t==1)<span class="veryLowRisk">{{ trans('global.low') }}</span>@endif
                            @if ($process->security_need_t==2)<span class="lowRisk">{{ trans('global.medium') }}</span>@endif
                            @if ($process->security_need_t==3)<span class="mediumRisk">{{ trans('global.strong') }}</span>@endif
                            @if ($process->security_need_t==4)<span class="highRisk">{{ trans('global.very_strong') }}</span>@endif
                        @if (config('mercator-config.parameters.security_need_auth'))
                        &nbsp;
                        {{ trans('global.authenticity') }} :
                            @if ($process->security_need_auth==0){{ trans('global.none') }}@endif
                            @if ($process->security_need_auth==1)<span class="veryLowRisk">{{ trans('global.low') }}</span>@endif
                            @if ($process->security_need_auth==2)<span class="lowRisk">{{ trans('global.medium') }}</span>@endif
                            @if ($process->security_need_auth==3)<span class="mediumRisk">{{ trans('global.strong') }}</span>@endif
                            @if ($process->security_need_auth==4)<span class="highRisk">{{ trans('global.very_strong') }}</span>@endif
                        @endif
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.process.fields.owner') }}
                        </th>
                        <td colspan="2">
                            {{ $process->owner }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.process.fields.macroprocessus') }}
                        </th>
                        <td colspan="2">
                            @if($process->macroProcess!=null)
                                <a href="{{ route('admin.macro-processuses.show', $process->macroProcess->id) }}">
                                    {{ $process->macroProcess->name }}
                                </a>
                            @endif
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer">
        {{ trans('global.created_at') }} {{ $process->created_at ? $process->created_at->format(trans('global.timestamp')) : '' }} |
        {{ trans('global.updated_at') }} {{ $process->updated_at ? $process->updated_at->format(trans('global.timestamp')) : '' }}
    </div>
</div>

<div class="form-group">
    <a class="btn btn-default" href="{{ route('admin.processes.index') }}">
        {{ trans('global.back_to_list') }}
    </a>
</div>
@endsection