routes/web.php
    Route::delete('network-switches-destroy', [Admin\NetworkSwitchController::class,'massDestroy'])->name('network-switches.massDestroy');

    // Routers
    Route::resource('routers', Admin\RouterController::class);
    Route::delete('routers-destroy', [Admin\RouterController::class,'massDestroy'])->name('routers.massDestroy');

    // Security Devices
    Route::resource('security-devices', Admin\SecurityDeviceController::class);
    Route::delete('security-devices-destroy', [Admin\SecurityDeviceController::class,'massDestroy'])->name('security-devices.massDestroy');

    // Dhcp Servers
    Route::resource('dhcp-servers', Admin\DhcpServerController::class);
    Route::delete('dhcp-servers-destroy', [Admin\DhcpServerController::class,'massDestroy'])->name('dhcp-servers.massDestroy');

    // Dnsservers
    Route::resource('dnsservers', Admin\DnsserverController::class);
    Route::delete('dnsservers-destroy', [Admin\DnsserverController::class,'massDestroy'])->name('dnsservers.massDestroy');

    // Clusters
    Route::resource('clusters', Admin\ClusterController::class);
    Route::delete('clusters-destroy', [Admin\ClusterController::class,'massDestroy'])->name('clusters.massDestroy');

    // Logical Servers
    Route::resource('logical-servers', Admin\LogicalServerController::class);
    Route::delete('logical-servers-destroy', [Admin\LogicalServerController::class,'massDestroy'])->name('logical-servers.massDestroy');

    // Containers
    Route::resource('containers', Admin\ContainerController::class);
    Route::delete('containers-destroy', [Admin\ContainerController::class,'massDestroy'])->name('containers.massDestroy');

    // Logical Flows
    Route::resource('logical-flows', Admin\LogicalFlowController::class);
    Route::delete('logical-flows-destroy', [Admin\LogicalFlowController::class,'massDestroy'])->name('logical-flows.massDestroy');

    // Certificates
    Route::resource('certificates', Admin\CertificateController::class);
    Route::delete('certificates-destroy', [Admin\CertificateController::class,'massDestroy'])->name('certificates.massDestroy');

    // Sites
    Route::resource('sites', Admin\SiteController::class);
    Route::get('sites-clone/{id}', [Admin\SiteController::class,'clone'])->name('sites.clone');
    Route::delete('sites-destroy', [Admin\SiteController::class,'massDestroy'])->name('sites.massDestroy');

    // Buildings
    Route::resource('buildings', Admin\BuildingController::class);
    Route::get('buildings-clone/{id}', [Admin\BuildingController::class,'clone'])->name('buildings.clone');
    Route::delete('buildings-destroy', [Admin\BuildingController::class,'massDestroy'])->name('buildings.massDestroy');

    // Bays
    Route::resource('bays', Admin\BayController::class);
    Route::get('bays-clone/{id}', [Admin\BayController::class,'clone'])->name('bays.clone');
    Route::delete('bays-destroy', [Admin\BayController::class,'massDestroy'])->name('bays.massDestroy');

    // Physical Servers
    Route::resource('physical-servers', Admin\PhysicalServerController::class);
    Route::get('physical-servers-clone/{id}', [Admin\PhysicalServerController::class,'clone'])->name('physical-servers.clone');
    Route::delete('physical-servers-destroy', [Admin\PhysicalServerController::class,'massDestroy'])->name('physical-servers.massDestroy');

    // Workstations
    Route::resource('workstations', Admin\WorkstationController::class);
    Route::get('workstations-clone/{id}', [Admin\WorkstationController::class,'clone'])->name('workstations.clone');
    Route::delete('workstations-destroy', [Admin\WorkstationController::class,'massDestroy'])->name('workstations.massDestroy');

    // Storage Devices
    Route::resource('storage-devices', Admin\StorageDeviceController::class);
    Route::delete('storage-devices-destroy', [Admin\StorageDeviceController::class,'massDestroy'])->name('storage-devices.massDestroy');

    // Peripherals
    Route::resource('peripherals', Admin\PeripheralController::class);
    Route::get('peripherals-clone/{id}', [Admin\PeripheralController::class,'clone'])->name('peripherals.clone');
    Route::delete('peripherals-destroy', [Admin\PeripheralController::class,'massDestroy'])->name('peripherals.massDestroy');

    // Phones
    Route::resource('phones', Admin\PhoneController::class);
    Route::get('phones-clone/{id}', [Admin\PhoneController::class,'clone'])->name('phones.clone');
    Route::delete('phones-destroy', [Admin\PhoneController::class,'massDestroy'])->name('phones.massDestroy');

    // Physical Switches
    Route::resource('physical-switches', Admin\PhysicalSwitchController::class);
    Route::get('physical-switches-clone/{id}', [Admin\PhysicalSwitchController::class,'clone'])->name('physical-switches.clone');
    Route::delete('physical-switches-destroy', [Admin\PhysicalSwitchController::class,'massDestroy'])->name('physical-switches.massDestroy');

    // Physical Routers
    Route::resource('physical-routers', Admin\PhysicalRouterController::class);
    Route::get('physical-routers-clone/{id}', [Admin\PhysicalRouterController::class,'clone'])->name('physical-routers.clone');
    Route::delete('physical-routers-destroy', [Admin\PhysicalRouterController::class,'massDestroy'])->name('physical-routers.massDestroy');

    // Wifi Terminals
    Route::resource('wifi-terminals', Admin\WifiTerminalController::class);
    Route::get('wifi-terminals-clone/{id}', [Admin\WifiTerminalController::class,'clone'])->name('wifi-terminals.clone');
    Route::delete('wifi-terminals-destroy', [Admin\WifiTerminalController::class,'massDestroy'])->name('wifi-terminals.massDestroy');

    // Physical Security Devices
    Route::resource('physical-security-devices', Admin\PhysicalSecurityDeviceController::class);
    Route::delete('physical-security-devices-destroy', [Admin\PhysicalSecurityDeviceController::class,'massDestroy'])->name('physical-security-devices.massDestroy');

    // Physical Links
    // TODO : check why it is not working with physical-links as resource name
    Route::resource('links', Admin\PhysicalLinkController::class);
    Route::delete('links-destroy', [Admin\PhysicalLinkController::class,'massDestroy'])->name('links.massDestroy');

    // WANs
    Route::resource('wans', Admin\WanController::class);
    Route::delete('wans-destroy', [Admin\WanController::class,'massDestroy'])->name('wans.massDestroy');

    // MANs
    Route::resource('mans', Admin\ManController::class);
    Route::delete('mans-destroy', [Admin\ManController::class,'massDestroy'])->name('mans.massDestroy');

    // LANs
    Route::resource('lans', Admin\LanController::class);
    Route::delete('lans-destroy', [Admin\LanController::class,'massDestroy'])->name('lans.massDestroy');

    // VLANs
    Route::resource('vlans', Admin\VlanController::class);
    Route::get('vlans/clone/{id}', [Admin\VlanController::class,'clone'])->name('vlans.clone');
    Route::delete('vlans-destroy', [Admin\VlanController::class,'massDestroy'])->name('vlans.massDestroy');

    // Application Modules
    Route::resource('application-modules', Admin\ApplicationModuleController::class);
    Route::delete('application-modules-destroy', [Admin\ApplicationModuleController::class,'massDestroy'])->name('application-modules.massDestroy');

    // Macro Processuses
    Route::resource('macro-processuses', Admin\MacroProcessusController::class);
    Route::delete('macro-processuses-destroy', [Admin\MacroProcessusController::class,'massDestroy'])->name('macro-processuses.massDestroy');

    // Global Search engine !
    Route::get('global-search', [Admin\GlobalSearchController::class,'search'])->name('globalSearch');

    // Certificate Configuration page
    Route::get('config/cert', [Admin\ConfigurationController::class,'getCertConfig'])->name('config.cert');
    Route::put('config/cert/save', [Admin\ConfigurationController::class,'saveCertConfig'])->name('config.cert.save');

    // CVE Configuration page
    Route::get('config/cve', [Admin\ConfigurationController::class,'getCVEConfig'])->name('config.cve');
    Route::put('config/cve/save', [Admin\ConfigurationController::class,'saveCVEConfig'])->name('config.cve.save');

    // Parameters
    Route::get('config/parameters', [Admin\ConfigurationController::class,'getParameters'])->name('config.parameters');
    Route::put('config/parameters/save', [Admin\ConfigurationController::class,'saveParameters'])->name('config.parameters.save');

    // Views
    // TODO : create a new class ViewController to reduce size of ReportController
    Route::get('report/gdpr', [Admin\ReportController::class, 'gdpr'])->name('report.gdpr');
    Route::get('report/ecosystem', [Admin\ReportController::class,'ecosystem'])->name('report.view.ecosystem');
    Route::get('report/information_system', [Admin\ReportController::class,'informationSystem'])->name('report.view.informaton-system');
    Route::get('report/administration', [Admin\ReportController::class,'administration'])->name('report.view.administration');
    Route::get('report/applications', [Admin\ReportController::class,'applications'])->name('report.view.applications');
    Route::get('report/application_flows', [Admin\ReportController::class,'applicationFlows'])->name('report.view.application-flows');
    Route::get('report/logical_infrastructure', [Admin\ReportController::class,'logicalInfrastructure'])->name('report.view.logical-infrastructure');
    Route::get('report/physical_infrastructure', [Admin\ReportController::class,'physicalInfrastructure'])->name('report.view.physical-infrastructure');
    Route::get('report/network_infrastructure', [Admin\ReportController::class,'networkInfrastructure'])->name('report.view.network-infrastructure');

    // Experimental views
    Route::get('report/zones', [Admin\ReportController::class,'zones'])->name('report.view.zones');

    // Graphs
    Route::resource('graphs', Admin\GraphController::class);

app/Workstation.php
<?php

namespace App;

use App\Traits\Auditable;
use DateTimeInterface;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * App\Workstation
 *
 * @mixin \Eloquent
 */
class Workstation extends Model
{
    use SoftDeletes, Auditable;

    public $table = 'workstations';

    public static $searchable = [
        'name',
        'type',
        'description',
    ];

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'name',
        'type',
        'description',
        'icon_id',
        'site_id',
        'building_id',
        'cpu',
        'memory',
        'disk',
        'operating_system',
        'address_ip',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public function site()
    {
        return $this->belongsTo(Site::class, 'site_id');
    }

    public function building()
    {
        return $this->belongsTo(Building::class, 'building_id');
    }

    public function applications()
    {
        return $this->belongsToMany(MApplication::class)->orderBy('name');
    }

    public function getFillable()
    {
        return $this->fillable;
    }

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/API/WorkstationController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyWorkstationRequest;
use App\Http\Requests\StoreWorkstationRequest;
use App\Http\Requests\UpdateWorkstationRequest;
use App\Http\Resources\Admin\WorkstationResource;
use App\Workstation;
use Gate;
use Illuminate\Http\Response;

class WorkstationController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('workstation_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $workstations = Workstation::all();

        return response()->json($workstations);
    }

    public function store(StoreWorkstationRequest $request)
    {
        abort_if(Gate::denies('workstation_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $workstation = Workstation::create($request->all());

        return response()->json($workstation, 201);
    }

    public function show(Workstation $workstation)
    {
        abort_if(Gate::denies('workstation_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return new WorkstationResource($workstation);
    }

    public function update(UpdateWorkstationRequest $request, Workstation $workstation)
    {
        abort_if(Gate::denies('workstation_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $workstation->update($request->all());

        return response()->json();
    }

    public function destroy(Workstation $workstation)
    {
        abort_if(Gate::denies('workstation_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $workstation->delete();

        return response()->json();
    }

    public function massDestroy(MassDestroyWorkstationRequest $request)
    {
        abort_if(Gate::denies('workstation_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        Workstation::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/workstations/index.blade.php
@extends('layouts.admin')
@section('content')
@can('workstation_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.workstations.create") }}">
                {{ trans('global.add') }} {{ trans('cruds.workstation.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.workstation.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table id="dataTable" class="table table-bordered table-striped table-hover datatable">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.workstation.fields.name') }}
                        </th>
                        <th>
                            {{ trans('cruds.workstation.fields.type') }}
                        </th>
                        <th>
                            {{ trans('cruds.workstation.fields.site') }}
                        </th>
                        <th>
                            {{ trans('cruds.workstation.fields.building') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($workstations as $key => $workstation)
                        <tr data-entry-id="{{ $workstation->id }}">
                            <td>

                            </td>
                            <td>
                                <a href="{{ route('admin.workstations.show', $workstation->id) }}">
                                {{ $workstation->name ?? '' }}
                                </a>
                            </td>
                            <td>
                                {!! $workstation->type ?? '' !!}
                            </td>
                            <td>
                                @if ($workstation->site!=null)
                                    <a href="{{ route('admin.sites.show', $workstation->site->id) }}">
                                        {{ $workstation->site->name ?? '' }}
                                    </a>
                                @endif
                            </td>
                            <td>
                                @if ($workstation->building!=null)
                                <a href="{{ route('admin.buildings.show', $workstation->building->id) }}">
                                    {{ $workstation->building->name ?? '' }}
                                </a>
                                @endif
                            </td>
                            <td nowrap>
                                @can('workstation_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.workstations.show', $workstation->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('workstation_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.workstations.edit', $workstation->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('workstation_delete')
                                    <form action="{{ route('admin.workstations.destroy', $workstation->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection

@section('scripts')
@parent
<script>
@include('partials.datatable', array(
    'id' => '#dataTable',
    'title' => trans("cruds.workstation.title_singular"),
    'URL' => route('admin.workstations.massDestroy'),
    'canDelete' => auth()->user()->can('workstation_delete') ? true : false
));
</script>
@endsection

resources/views/admin/workstations/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="form-group">
    <div class="form-group">
        <a class="btn btn-default" href="{{ route('admin.workstations.index') }}">
            {{ trans('global.back_to_list') }}
        </a>

        <a class="btn btn-success" href="{{ route('admin.report.explore') }}?node=WORK_{{$workstation->id}}">
            {{ trans('global.explore') }}
        </a>

        @can('workstation_edit')
            <a class="btn btn-info" href="{{ route('admin.workstations.edit', $workstation->id) }}">
                {{ trans('global.edit') }}
            </a>
        @endcan

        @can('workstation_create')
            <a class="btn btn-warning" href="{{ route('admin.workstations.clone', $workstation->id) }}">
                {{ trans('global.clone') }}
            </a>
        @endcan

        @can('workstation_delete')
            <form action="{{ route('admin.workstations.destroy', $workstation->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                <input type="hidden" name="_method" value="DELETE">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                <input type="submit" class="btn btn-danger" value="{{ trans('global.delete') }}">
            </form>
        @endcan
    </div>

<div class="card">
    <!---------------------------------------------------------------------------------------------------->
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.workstation.title') }}
    </div>
    <!---------------------------------------------------------------------------------------------------->
    <div class="card-body">
        <div class="row">
            <div class="col-md-6">
                <dt>{{ trans('cruds.workstation.fields.name') }}</dt>
                {{ $workstation->name }}
            </div>
            <div class="col-md-6">
                <dt>{{ trans('cruds.workstation.fields.type') }}</dt>
                {{ $workstation->type }}
            </div>
        </div>
        <div class="row">
            <div class="col-md-9">
                <dt>{{ trans('cruds.workstation.fields.description') }}</dt>
                {!! $workstation->description !!}
            </div>
            <div class="col-md-3">
                <img src="{{ $workstation->icon_id === null ? '/images/workstation.png' : route('admin.documents.show', $workstation->icon_id) }}" width='120' height='120'/>
            </div>
        </div>
    </div>
    <!---------------------------------------------------------------------------------------------------->
    <div class="card-header">
        {{ trans("cruds.menu.application.title_short") }}
    </div>
    <!---------------------------------------------------------------------------------------------------->
    <div class="card-body">
        <div class="row">
            <div class="col-sm">
                <dt>{{ trans('cruds.workstation.fields.applications') }}</dt>
                @foreach($workstation->applications as $application)
                    <a href="{{ route('admin.applications.show', $application->id) }}">
                        {{ $application->name }}
                    </a>
                    @if(!$loop->last)
                    ,
                    @endif
                @endforeach
            </div>
        </div>
    </div>
    <!---------------------------------------------------------------------------------------------------->
    <div class="card-header">
        {{ trans("cruds.menu.logical_infrastructure.title_short") }}
    </div>
    <!---------------------------------------------------------------------------------------------------->
    <div class="card-body">
        <div class="row">
            <div class="col-sm-2">
                <b>{{ trans('cruds.workstation.fields.cpu') }}</b>
                {{ $workstation->cpu }}
            </div>
            <div class="col-sm-2">
                <b>{{ trans('cruds.workstation.fields.memory') }}</b>
                {{ $workstation->memory }}
            </div>
            <div class="col-sm-2">
                <b>{{ trans('cruds.workstation.fields.disk') }}</b>
                {{ $workstation->disk }}
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <dt>{{ trans('cruds.workstation.fields.operating_system') }}</dt>
                {!! $workstation->operating_system !!}
            </div>
            <div class="col-sm-4">
                <dt>{{ trans('cruds.workstation.fields.address_ip') }}</dt>
                {!! $workstation->address_ip !!}
            </div>
        </div>
    </div>
    <!---------------------------------------------------------------------------------------------------->
    <div class="card-header">
        {{ trans("cruds.menu.physical_infrastructure.title_short") }}
    </div>
    <!---------------------------------------------------------------------------------------------------->
    <div class="card-body">
        <div class="row">
            <div class="col-lg">
                <b>{{ trans('cruds.workstation.fields.site') }}</b>
                {{ $workstation->site->name ?? '' }}
            </div>
        </div>
        <div class="row">
            <div class="col-lg">
                <b>{{ trans('cruds.workstation.fields.building') }}</b>
                {{ $workstation->building->name ?? '' }}
            </div>
        </div>
    </div>
    <div class="card-footer">
        {{ trans('global.created_at') }} {{ $workstation->created_at ? $workstation->created_at->format(trans('global.timestamp')) : '' }} |
        {{ trans('global.updated_at') }} {{ $workstation->updated_at ? $workstation->updated_at->format(trans('global.timestamp')) : '' }}
    </div>
</div>
<div class="form-group">
    <a class="btn btn-default" href="{{ route('admin.workstations.index') }}">
        {{ trans('global.back_to_list') }}
    </a>

@endsection